### ISSUE TITLE
Video pixel format may not be coherent with texture copy

### ISSUE THREAD

**Issue by bokuwatoritori** [gmounie/ensimag-video#3]
[Pixel format in Theora](https://www.theora.org/doc/libtheora-1.0/codec_8h.html#4ce7a695ce353b1582d29b6c1ddf31a0) may change width/height for each chroma plane.
  - For the pixel format TH_PF_420, Cb and Cr chroma planes are half width and half height of the luma plane.
  - For the pixel format TH_PF_422, Cb and Cr chroma planes are half width of the luma plane and full height.
  - For the pixel format TH_PF_444, Cb and Cr chroma planes are full width/height.

In the first 2 cases, the copying loop in theora2SDL from ensitheora.c may fail since windowsx and windowsy are based on the luma plane. Also, the allocating of the planes use more space than it have to.

**Comment by mathieu-porcel** [comment]
This code should fix the problem for most of the cases:
```c
// copy data in the current texturedate
for (int i=0; i < 3; i++) {
  for (int y=0; y < videobuffer[i].height; y++) {
    memmove(texturedate[tex_iwri].plane[i]+y*windowsx,
      videobuffer[i].data + y*videobuffer[i].stride, videobuffer[i].width);
  }
}

**Comment by gmounie** [comment]
Applied in master and develop branch ! Thanks for the correction.
